# Workflow derived from https://community.rstudio.com/t/deploying-shiny-app-with-github-actions/78436
on:
  push:
    branches: [main, master]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            pkgload
            rsconnect
            here

      - name: Push to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name = 'aldomann', token = Sys.getenv('SHINYAPPS_TOKEN'), secret = Sys.getenv('SHINYAPPS_SECRET'))"
          Rscript -e "rsconnect::deployApp(appName = 'biodosetools-dev', appDir = here::here(), appFileManifest = here::here('dev/app_file_manifest.txt'), forceUpdate = TRUE)"
